# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: php

# Travis support wrote "Ubuntu 14.04 reached EOL on April 30th, 2019,
# ... we've been slowly rolling out changes to make Xenial builds ..."
# https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
# https://docs.travis-ci.com/user/reference/xenial/#services-disabled-by-default.
services:
  - mysql

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=REL1_32; TYPE=coverage; PHPUNIT=6.5.*
      php: 7.1
    - env: DB=sqlite; MW=REL1_32; SITELANG=ja; PHPUNIT=6.5.*
      php: 7.1
    - env: DB=postgres; MW=REL1_34; PHPUNIT=6.5.*;
      php: 7.2
    - env: DB=mysql; MW=master; PHPUNIT=8.5.*
      php: 7.4
  allow_failures:
    - env: DB=mysql; MW=master; PHPUNIT=8.5.*

install:
  - composer self-update
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-image-caption.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

cache:
  directories:
    - $HOME/.composer/cache
